version: '3.7'
services:
  krakend-1:
    image: devopsfaith/krakend:watch
    volumes:
      - ./src:/etc/krakend
    ports:
      - 8080:8080
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
  krakend-2:
    image: devopsfaith/krakend:watch
    volumes:
      - ./src:/etc/krakend
    ports:
      - 8081:8080
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
  redis:
    image: redis:6.2
    hostname: redis
    ports:
      - 6379:6379
    
